In [28]:
import numpy as np
a = np.array([10, 20, 30, 40,50])
print(a)
print(np.zeros((2,3)))
print(np.ones((1,2)))
print(np.linspace(1,5,10))
a

[10 20 30 40 50]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


array([10, 20, 30, 40, 50])

In [29]:
print(a.dtype)
print(a.shape)
print(a.size)
print(a.ndim)

int32
(5,)
5
1


In [42]:
x=np.arange(1,6)
print(x)
print(np.add(a,x))
print(np.multiply(a,x))
print(np.sqrt(a))
print(np.exp(x))
print(np.log(x))

[1 2 3 4 5]
[11 22 33 44 55]
[ 10  40  90 160 250]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [45]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.argmin(x))
print(np.argmax(x))

30.0
30.0
14.142135623730951
200.0
150
10
50
0
4


In [48]:
b=np.arange(10,70,10)
print(b)
labels=np.where(b>25,'High', 'Low')
conditions=[b<15,(b>=15)&(b<35),b>=35]
choices=['Low',  'Medium', 'High']
result=np.select(conditions, choices, default='Unknown')
p=np.logical_and(b>15 , b<45)
q=np.logical_or(b<20, b>35)
print(labels)
print(result)
print(b[p])
print(b[q])
print(np.logical_not(b>25))

[10 20 30 40 50 60]
['Low' 'Low' 'High' 'High' 'High' 'High']
['Low' 'Medium' 'Medium' 'High' 'High' 'High']
[20 30 40]
[10 40 50 60]
[ True  True False False False False]


In [55]:
r=b.reshape((2,3))
print(r)
r.flatten()

[[10 20 30]
 [40 50 60]]


array([10, 20, 30, 40, 50, 60])

In [59]:
print(r[0])
print(r[1][2])
print(r[0:1,2:])

[10 20 30]
60
[[30]]


In [61]:
y=np.array([[1,2,np.nan],[4,np.inf,6],[np.nan,8,9]])
print(y)

[[ 1.  2. nan]
 [ 4. inf  6.]
 [nan  8.  9.]]


In [62]:
np.isnan(y)

array([[False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [63]:
np.isinf(y)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [64]:
np.isfinite(y)

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

In [67]:
y[np.isfinite(y)]

array([1., 2., 4., 6., 8., 9.])

In [69]:
y[np.isnan(y)]=0
print(y)

[[ 1.  2.  0.]
 [ 4. inf  6.]
 [ 0.  8.  9.]]


In [70]:
np.nanmean(y)

inf

In [82]:
y=np.array([1,np.nan,3,np.inf,5])
y[np.isinf(y)]=np.nanmin(y)
y

array([ 1., nan,  3.,  1.,  5.])

In [85]:
np.random.rand(5)

array([[ 0.98095339,  0.8600144 ,  0.47698443],
       [-0.40090287,  1.29511113, -0.37205465]])

In [86]:
np.random.randn(2,3)

array([[-1.49442527,  0.67294397, -0.3908841 ],
       [ 0.23252495, -0.88703927, -0.62453927]])

In [87]:
np.random.randint(1,10)

5

In [89]:
arr=np.array([1,2,3,4,5])
np.random.choice(arr)

4

In [92]:
np.random.shuffle(arr)
arr

array([1, 4, 2, 5, 3])

In [93]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])

In [95]:
m1.T

array([[1, 3],
       [2, 4]])

In [96]:
np.linalg.inv(m2)

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [97]:
np.linalg.det(m1)

-2.0000000000000004

In [98]:
np.linalg.matrix_rank(m1)

2

In [100]:
np.linalg.eig(m2)

EigResult(eigenvalues=array([-0.15206735, 13.15206735]), eigenvectors=array([[-0.75868086, -0.59276441],
       [ 0.65146248, -0.80537591]]))

In [101]:
np.linalg.solve(m1,m2)

array([[-3., -4.],
       [ 4.,  5.]])